routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

	if ( auth()->id() ) {

		return redirect()->route('home');
	}

    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('base-sheets', 'BaseSheetController');
Route::resource('press-sheets', 'PressSheetController');
Route::get('press-sheets/create/{baseSheetId?}', 'PressSheetController@create')->name('press-sheets.create');
Route::post('press-sheets/filter', 'PressSheetController@filter')->name('press-sheets.filter');
Route::resource('clients', 'ClientController');
Route::resource('papers', 'PaperController');
Route::resource('machines', 'MachineController');



// Route::fallback(function () {
//     return view('welcome');
// });

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = [
        'contact_name',
        'business_name',
        'address',
        'notes',
        'pib',
        'email',
        'tel',
        'mb'
    ];
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ClientRequest;
use App\Services\ClientService;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    const ATTRIBUTES = [
        'contact_name',
        'business_name',
        'address',
        'notes',
        'pib',
        'email',
        'tel',
        'mb'
    ];
    const PER_PAGE = 50;
    const ORDER = 'desc';
    const BY = 'contact_name';

    private $clientService;
    
    public function __construct( ClientService $clientService ) {
        
        $this->middleware(['auth', 'verified']);

        $this->clientService = $clientService;
    }
    
    public function index( Request $request ) {

        $order = $request->order ?? self::ORDER;
        $by = $request->by ?? self::BY;

        $clients = $this->clientService->getAllPaginated( $order, $by, self::PER_PAGE );

        return view( 'clients.index', compact( 'clients', 'order', 'by' ) );
    }

    public function create() {
        
        return view('clients.create');
    }

    public function store( ClientRequest $request ) {

        $attributes = $request->only( self:: ATTRIBUTES );
        
        try {

            $this->clientService->store( $attributes );

        } catch (\Exception $exception) {
            return redirect()->back()
                ->with([
                    'status'  => 'danger',
                    'message' => 'Error: ' . $exception->getMessage()
                ])
                ->withInput();
        }

        $message = __('New client data saved');

        return redirect()->back()->with([
                    'status'  => 'success',
                    'message' => $message
                ])->withInput();
    }

    public function edit( Int $id ) {
        
        $client = $this->clientService->getById( $id );

        return view( 'clients.edit', compact('client') );
    }

    public function update( ClientRequest $request, Int $id ) {
        
        $attributes = $request->only(self::ATTRIBUTES);

        try {

            $this->clientService->update( $id, $attributes );

        } catch (Exception $exception) {
            
            return redirect()->back()
                ->with([
                    'status'  => 'danger',
                    'message' => 'Error: ' . $exception->getMessage()
                ])
                ->withInput();

        }

        return redirect()->back()->withInput();
    }

    public function destroy( Int $id ) {
        
        try {

            $this->clientService->delete( $id );

        } catch (Exception $exception) {
            
            return redirect()->back()
                ->with([
                    'status'  => 'danger',
                    'message' => 'Error: ' . $exception->getMessage()
                ])
                ->withInput();
        }

        $message = __('Client deleted.');

        return redirect()->route('clients.index')->with([
                    'status'  => 'success',
                    'message' => $message
                ]);
    }
}

resources/views/clients/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="">

        <form action="{{ route('clients.store') }}" method="POST" class="row px-3 needs-validation" novalidate>

            @csrf

            <div class="col">

                <div class="row">
                    <div class="col">
                        
                        <h1 class="mt-5 mb-2">{{ __('Address book') }}</h1>

                        <h2>{{ __('Add new client') }}</h2>
                        <hr>

                        @include('partials.alerts')

                        @include('clients.form-fields')

                    </div>
                </div>

            </div>


            <div id="sidebar" class="col-auto">

                <div class="text-center mt-5">
                    <button type="submit" class="btn btn-primary my-1 w-100">{{ __('Save') }}</button>
                    <a href="{{ route('clients.index') }}" class="btn btn-secondary my-1 w-100">{{ __('Cancel') }}</a>
                    
                    <br/>

                    <a class="btn btn-secondary my-1 w-100" href="/">{{ __('Back to home page') }}</a>
                </div>

            </div>

        </form>

    </div>

</div>

@endsection

resources/views/clients/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="">

        <form action="{{ route('clients.update', $client->id )}}" method="POST" class="row px-3 needs-validation" novalidate>

            @csrf
            @method('PATCH')

            <input type="number" class="d-none" name="id" value="{{ $client->id }}" />

            <div class="col">

            	<div class="row">
            		<div class="col">
            			
            			<h1 class="mt-5 mb-2">{{ __('Address book') }}</h1>

            			<h2>{{ __('Edit entry') }}</h2>
		            	<hr>

                        @include('partials.alerts')

                        @include('clients.form-fields')

            		</div>
            	</div>

            </div>


            <div id="sidebar" class="col-auto">

                <div class="text-center mt-5">
                    <button type="submit" class="btn btn-primary my-1 w-100">{{ __('Save') }}</button>
                    <a href="#" class="btn btn-danger my-1 w-100" onclick="if(confirm('{{ __('Are you sure?') }}')){
                        event.preventDefault();document.getElementById('delete_client').submit()
                    }">{{ __('Delete') }}</a>
                    <a href="{{ route('clients.index') }}" class="btn btn-secondary my-1 w-100">{{ __('Cancel') }}</a>
                    
                    <br/>

                    <a class="btn btn-secondary my-1 w-100" href="/">{{ __('Back to home page') }}</a>
                </div>
                
            </div>

        </form>

    </div>

</div>


<form id="delete_client" action="{{ route('clients.destroy', $client->id) }}"
      method="POST" style="display: none;" onsubmit="return confirm('{{ __('Are you sure?') }}')">
    @method('DELETE')
    @csrf
</form>

@endsection

resources/views/clients/form-fields.blade.php
<div class="form-group row">
    <label for="contact_name" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Contact') }}</label>
    <div class="col-lg-5">
        <input type="text" class="form-control form-control-sm {{ $errors->has('contact_name') ? 'is-invalid' : '' }}" id="contact_name" name="contact_name" placeholder="[{{ __('contact name') }}]" value="{{ old('contact_name', $client->contact_name ?? '') }}" required />
        <div class="invalid-feedback">
            @if ($errors->has('contact_name'))
                @foreach ($errors->get('contact_name') as $message)
                    {{ $message }}
                @endforeach
            @else
                {{ __('This field is mandatory!') }}
            @endif
        </div>
    </div>
</div>

<div class="form-group row">
    <label for="business_name" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Company') }}</label>
    <div class="col-lg-5">
        <input type="text" class="form-control form-control-sm {{ $errors->has('business_name') ? 'is-invalid' : '' }}" id="business_name" name="business_name" placeholder="[{{ __('Company') }}]" value="{{ old('business_name', $client->business_name ?? '') }}" required />
        <div class="invalid-feedback">
            @if ($errors->has('business_name'))
               @foreach ($errors->get('business_name') as $message)
                    {{ $message }}
                @endforeach
            @else
                {{ __('This field is mandatory!') }}
            @endif
        </div>
    </div>
</div>

<div class="form-group row">
    <label for="address" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Address') }}</label>
    <div class="col-lg-5">
        <textarea type="text" class="form-control form-control-sm" id="address" name="address" rows="3" placeholder="[{{ __('Address') }}]">{{ old('address', $client->address ?? '') }}</textarea>
    </div>
</div>

<div class="form-group row">
    <label for="pib" class="col-lg-2 col-form-label col-form-label-sm">{{ __('VAT number') }}</label>
    <div class="col-lg-5">
        <input type="number" step="1" class="form-control form-control-sm {{ $errors->has('pib') ? 'is-invalid' : '' }}" id="pib" name="pib" placeholder="[{{ __('VAT number') }}]" value="{{ old('pib', $client->pib ?? '') }}" required />
        <div class="invalid-feedback">
            @if ($errors->has('pib'))
               @foreach ($errors->get('pib') as $message)
                    {{ $message }}
                @endforeach
            @else
                {{ __('This field is mandatory!') }}
            @endif
        </div>
    </div>
</div>

<div class="form-group row">
    <label for="mb" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Registration number') }}</label>
    <div class="col-lg-5">
        <input type="number" step="1" class="form-control form-control-sm {{ $errors->has('mb') ? 'is-invalid' : '' }}" id="mb" name="mb" placeholder="[{{ __('Registration number') }}]" value="{{ old('mb', $client->mb ?? '') }}" />
        <div class="invalid-feedback">
            @if ($errors->has('mb'))
               @foreach ($errors->get('mb') as $message)
                    {{ $message }}
                @endforeach
            @else
                {{ __('This field is mandatory!') }}
            @endif
        </div>
    </div>
</div>

<div class="form-group row">
    <label for="email" class="col-lg-2 col-form-label col-form-label-sm">Email</label>
    <div class="col-lg-5">
        <input type="text" class="form-control form-control-sm {{ $errors->has('email') ? 'is-invalid' : '' }}" id="email" name="email" placeholder="[email]" value="{{ old('email', $client->email ?? '') }}" required />
        <div class="invalid-feedback">
            @if ($errors->has('email'))
                @foreach ($errors->get('email') as $message)
                    {{ $message }}
                @endforeach
            @else
                {{ __('This field is mandatory!') }}
            @endif
        </div>
    </div>
</div>

<div class="form-group row">
    <label for="tel" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Telephone') }}</label>
    <div class="col-lg-5">
        <input type="text" class="form-control form-control-sm" id="tel" name="tel" placeholder="[tel]" value="{{ old('tel', $client->tel ?? '') }}" />
    </div>
</div>

<div class="form-group row">
    <label for="notes" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Notes') }}</label>
    <div class="col-lg-5">
        <textarea type="text" class="form-control form-control-sm" id="notes" name="notes" rows="3" placeholder="[{{ __('Notes') }}]">{{ old('notes', $client->notes ?? '') }}</textarea>
    </div>
</div>

resources/views/clients/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="">

        <form class="row px-3">

            @csrf

            <div class="col">

            	<div class="row">
            		<div class="col">
            			
            			<h1 class="mt-5 mb-2">{{ __('Address book') }}</h1>

            			<h2>{{ __('Clients') }}</h2>
		            	<hr>

		            	@include('partials.alerts')

		            	<div>
					        <table class="ck" data-sort="table">
					            <thead>
					            <tr>
					            	<th class="header header-sort-{{ $by === 'contact_name' ? ($order === 'desc' ? 'down' : 'up') : '' }}">
					                	<a href="{{ request()->fullUrlWithQuery(['by' => 'contact_name', 'order' => $order === 'desc' ? 'asc' : 'desc']) }}">{{ __('Contact') }}</a>
						            </th><th class="header header-sort-{{ $by === 'business_name' ? ($order === 'desc' ? 'down' : 'up') : '' }}">
					                	<a href="{{ request()->fullUrlWithQuery(['by' => 'business_name', 'order' => $order === 'desc' ? 'asc' : 'desc']) }}">{{ __('Company') }}</a>
						            </th><th class="header header-sort-{{ $by === 'address' ? ($order === 'desc' ? 'down' : 'up') : '' }}">
					                	<a href="{{ request()->fullUrlWithQuery(['by' => 'address', 'order' => $order === 'desc' ? 'asc' : 'desc']) }}">{{ __('Address') }}</a>
						            </th><th class="header header-sort-{{ $by === 'email' ? ($order === 'desc' ? 'down' : 'up') : '' }}">
					                	<a href="{{ request()->fullUrlWithQuery(['by' => 'email', 'order' => $order === 'desc' ? 'asc' : 'desc']) }}">Email</a>
						            </th><th class="header header-sort-{{ $by === 'tel' ? ($order === 'desc' ? 'down' : 'up') : '' }}">
					                	<a href="{{ request()->fullUrlWithQuery(['by' => 'tel', 'order' => $order === 'desc' ? 'asc' : 'desc']) }}">{{ __('Telephone') }}</a>
						            </th>
					                <th class="header">{{ __('Edit') }}</th>
					            </tr>
					            </thead>
					            <tbody>
					            	@if($clients->count())
					            		@foreach ($clients as $client)
							                <tr class="clickable-row" data-href="{{ route('clients.edit', $client->id) }}">
							                    <td>{{ $client->contact_name }}</td>
							                    <td>{{ $client->business_name }}</td>
							                    <td>{{ $client->address }}</td>
							                    <td>{{ $client->email }}</td>
							                    <td>{{ $client->tel }}</td>
							                    <td><i class="fa fa-caret-right"></i></td>
							                </tr>
							            @endforeach
						              @else
						              	<tr class="clickable-row" data-href="">
						                    <td colspan="6">{{ __('No entries') }}</td>
						                </tr>
						              @endif
					            </tbody>
					        </table>
					    </div>

					    <div class="pagination mt-5 w-100 align-items-center">

					    	{{ $clients->links() }}

					    </div>

            		</div>
            	</div>

            </div>


            <div id="sidebar" class="col-auto">

                <div class="text-center mt-5">
                    <a class="btn btn-primary my-1 w-100" href="{{ route('clients.create') }}">{{ __('Add new client') }}</a>
                    
                    <br/>

                    <a class="btn btn-secondary my-1 w-100" href="/">{{ __('Back to home page') }}</a>
                </div>
                
            </div>

        </form>

    </div>

</div>

@endsection