routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

	if ( auth()->id() ) {

		return redirect()->route('home');
	}

    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('base-sheets', 'BaseSheetController');
Route::resource('press-sheets', 'PressSheetController');
Route::get('press-sheets/create/{baseSheetId?}', 'PressSheetController@create')->name('press-sheets.create');
Route::post('press-sheets/filter', 'PressSheetController@filter')->name('press-sheets.filter');
Route::resource('clients', 'ClientController');
Route::resource('papers', 'PaperController');
Route::resource('machines', 'MachineController');



// Route::fallback(function () {
//     return view('welcome');
// });

app/Paper.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Paper extends Model
{
    const TABLE = 'papers';
    
    protected $table = self::TABLE; 

    protected $fillable = [
        'name',
        'description',
        'price_per_kg',
        'price_per_sheet',
        'specific_weight',
        'base_sheet_id'
    ];

    public function baseSheet()
	{
	    return $this->belongsTo(BaseSheet::class);
	}
}

app/Http/Controllers/PaperController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PaperRequest;
use App\Paper;
use App\Services\BaseSheetService;
use App\Services\PaperService;
use Illuminate\Http\Request;

class PaperController extends Controller
{
    const ATTRIBUTES = [
        'name',
        'description',
        'price_per_kg',
        'price_per_sheet',
        'specific_weight',
        'base_sheet_id'
    ];
    const PER_PAGE = 50;
    const ORDER = 'asc';
    const BY = 'name';

    private $basesSheetService;
    private $paperService;
    
    public function __construct( BaseSheetService $baseSheetService, PaperService $paperService ) {
        
        $this->middleware(['auth', 'verified']);

        $this->baseSheetService = $baseSheetService;
        $this->paperService = $paperService;
    }
    
    public function index( Request $request ) {

        $base_sheets = $this->baseSheetService->getAll();

        if ( $base_sheets->count() ) {

            $order = $request->order ?? self::ORDER;
            $by = $request->by ?? self::BY;
            $papers = $this->paperService->getAllPaginated( $order, $by, self::PER_PAGE );

            return view('papers.index', compact('papers', 'order', 'by'));
        }

        $error = __('You must define at least one base sheet first.');

        return redirect()->route('home')->with([
                    'status'  => 'danger',
                    'message' => $error
                ]);
    }

    public function create() {
        
        $base_sheets = $this->baseSheetService->getAll();

        return view('papers.create', compact('base_sheets'));
    }

    public function store( PaperRequest $request ) {
        
        $attributes = $request->only(self::ATTRIBUTES);

        try {

            $this->paperService->store( $attributes );

        }  catch (\Exception $exception) {
            return redirect()->back()
                ->with([
                    'status'  => 'danger',
                    'message' => 'Error: ' . $exception->getMessage()
                ])
                ->withInput();
        }

       return redirect()->route('papers.index');
    }

    public function edit( Int $id ) {

        $base_sheets = $this->baseSheetService->getAll();
        
        if ( $paper = $this->paperService->getById( $id ) ) {

            return view( 'papers.edit', compact( 'paper', 'base_sheets' ) );
        }

        return redirect()->route( 'papers.index' );
    }

    public function update( PaperRequest $request, Int $id ) {
        
        $attributes = $request->only(self::ATTRIBUTES);

        try {

            $this->paperService->update( $id, $attributes );

        } catch (Exception $exception) {
            
            return redirect()->back()
                ->with([
                    'status'  => 'danger',
                    'message' => 'Error: ' . $exception->getMessage()
                ])
                ->withInput();
        }

        return redirect()->back();
    }

    public function destroy( Int $id ) {
        
        try {

            $this->paperService->delete( $id );

        } catch (Exception $exception) {
            
            return redirect()->back()
                ->with([
                    'status'  => 'danger',
                    'message' => 'Error: ' . $exception->getMessage()
                ])
                ->withInput();
        }

        $message = __('Paper deleted.');

        return redirect()->route('papers.index')->with([
                    'status'  => 'success',
                    'message' => $message
                ]);
    }
}

resources/views/papers/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="">

        <form action="{{ route('papers.store') }}" method="POST" class="row px-3 needs-validation" novalidate>

            @csrf

            <div class="col">

                <div class="row">
                    <div class="col">
                        
                        <h1 class="mt-5">{{ __('Papers') }}</h1>

                        <h2>{{ __('Add new paper') }}</h2>
                        <hr>

                        @include('partials.alerts')

                        @include('papers.form-fields')

                    </div>
                </div>

            </div>


            <div id="sidebar" class="col-auto">

                <div class="text-center mt-5">
                    <button type="submit" class="btn btn-primary my-1 w-100">{{ __('Save') }}</button>
                    <a href="{{ route('papers.index') }}" class="btn btn-secondary my-1 w-100">{{ __('Cancel') }}</a>
                    
                    <br/>

                    <a class="btn btn-secondary my-1 w-100" href="/">{{ __('Back to home page') }}</a>
                </div>
                
            </div>

        </form>

    </div>

</div>

@endsection

resources/views/papers/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="">

        <form action="{{ route('papers.update', $paper->id )}}" method="POST" class="row px-3 needs-validation" novalidate>

            @csrf
            @method('PATCH')

            <input type="number" class="d-none" name="id" value="{{ $paper->id }}" />

            <div class="col">

                <div class="row">
                    <div class="col">
                        
                        <h1 class="mt-5">{{ __('Papers') }}</h1>

                        <h2>{{ __('Edit') }}</h2>
                        <hr>

                        @include('partials.alerts')

                        @include('papers.form-fields')

                    </div>
                </div>

            </div>


            <div id="sidebar" class="col-auto">

                <div class="text-center mt-5">
                    <button type="submit" class="btn btn-primary my-1 w-100">{{ __('Save') }}</button>

                    <a href="#" class="btn btn-danger my-1 w-100" onclick="if(confirm('{{ __('Are you sure?') }}')){
                        event.preventDefault();document.getElementById('delete_paper').submit()
                    }">{{ __('Delete') }}</a>

                    <a href="{{ route('papers.index') }}" class="btn btn-secondary my-1 w-100">{{ __('Cancel') }}</a>
                    
                    <br/>

                    <a class="btn btn-secondary my-1 w-100" href="/">{{ __('Back to home page') }}</a>
                </div>
                
            </div>

        </form>

    </div>

</div>


<form id="delete_paper" action="{{ route('papers.destroy', $paper->id) }}"
      method="POST" style="display: none;" onsubmit="return confirm('{{ __('Are you sure?') }}')">
    @method('DELETE')
    @csrf
</form>

@endsection

resources/views/papers/form-fields.blade.php
<div>
    <div class="form-group row">
        <label for="name" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Title') }}</label>
        <div class="col-lg-5">
            <input type="text" class="form-control form-control-sm {{ $errors->has('name') ? 'is-invalid' : '' }}" id="name" name="name" placeholder="[{{ __('Title') }}]" value="{{ old('name', $paper->name ?? '') }}" required />
            <div class="invalid-feedback">
                @if ($errors->has('name'))
                    @foreach ($errors->get('name') as $message)
                        {{ $message }}
                    @endforeach
                @else
                    {{ __('This field is mandatory!') }}
                @endif
            </div>
        </div>
    </div>                            
    
    <div class="form-group row">
        <label for="description" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Description') }}</label>
        <div class="col-lg-5">
            <textarea type="text" class="form-control form-control-sm" id="description" name="description" rows="3" placeholder="[{{ __('Description') }}]">{{ old('description', $paper->description ?? '') }}</textarea>
        </div>
    </div>

    <div class="form-group row">
        <label for="price_per_kg" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Price per kg') }}</label>
        <div class="col-lg-5">
            <input type="number" step="0.01" class="form-control form-control-sm {{ $errors->has('price_per_kg') ? 'is-invalid' : '' }}" id="price_per_kg" name="price_per_kg" placeholder="[eur]" value="{{ old('price_per_kg', $paper->price_per_kg ?? '') }}" />
            <div class="invalid-feedback">
                @if ($errors->has('price_per_kg'))
                   @foreach ($errors->get('price_per_kg') as $message)
                        {{ $message }}
                    @endforeach
                @endif
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="price_per_sheet" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Price per sheet') }}</label>
        <div class="col-lg-5">
            <input type="number" step="0.01" class="form-control form-control-sm {{ $errors->has('price_per_sheet') ? 'is-invalid' : '' }}" id="price_per_sheet" name="price_per_sheet" placeholder="[eur]" value="{{ old('price_per_sheet', $paper->price_per_sheet ?? '') }}" />
            <div class="invalid-feedback">
                @if ($errors->has('price_per_sheet'))
                   @foreach ($errors->get('price_per_sheet') as $message)
                        {{ $message }}
                    @endforeach
                @endif
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="specific_weight" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Specific weights') }} ({{ __('[kg/3] - separate them by comma') }})</label>
        <div class="col-lg-5">
            <input type="text" class="form-control form-control-sm {{ $errors->has('specific_weight') ? 'is-invalid' : '' }}" id="specific_weight" name="specific_weight" placeholder="[80,100,120,135...]" value="{{ old('specific_weight', $paper->specific_weight ?? '') }}" />
            <div class="invalid-feedback">
                @if ($errors->has('specific_weight'))
                   @foreach ($errors->get('specific_weight') as $message)
                        {{ $message }}
                    @endforeach
                @endif
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="base_sheet_id" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Dimensions (defined in base sheet)') }}</label>
        <div class="col-lg-5">
            <select class="form-control form-control-sm col-12 px-0" id="base_sheet_id {{ $errors->has('base_sheet_id') ? 'is-invalid' : '' }}" name="base_sheet_id" required>
                <option value="">({{ __('pick a base sheet') }} - {{ __('This field is mandatory!') }})</option>
                @foreach($base_sheets as $base_sheet)
                    <option value="{{ $base_sheet['id'] }}" {{ ($base_sheet['id'] == old('base_sheet_id', $paper->base_sheet_id ?? '')) ? 'selected' : '' }}>
                        {{ $base_sheet['name'] }}
                    </option>
                @endforeach
            </select>
            <div class="invalid-feedback">
                @if ($errors->has('base_sheet_id'))
                   @foreach ($errors->get('base_sheet_id') as $message)
                        {{ $message }}
                    @endforeach
                @else
                    {{ __('This field is mandatory!') }}
                @endif
            </div>
        </div>
    </div>
</div>

resources/views/papers/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="">

        <form class="row px-3">

            @csrf

            <div class="col">

            	<div class="row">
            		<div class="col">
            			
            			<h1 class="mt-5 mb-2">{{ __('Papers') }}</h1>

            			<h2>{{ __('Here you can define papers - price and dimensions') }}</h2>
		            	<hr>

		            	@include('partials.alerts')

		            	<div>
					        <table class="ck" data-sort="table">
					            <thead>
					            <tr>
					            	<th class="header header-sort-{{ $by === 'name' ? ($order === 'desc' ? 'down' : 'up') : '' }}">
					                	<a href="{{ request()->fullUrlWithQuery(['by' => 'name', 'order' => $order === 'desc' ? 'asc' : 'desc']) }}">{{ __('Title') }}</a>
						            </th>
						            <th class="header header-sort-{{ $by === 'description' ? ($order === 'desc' ? 'down' : 'up') : '' }}">
					                	<a href="{{ request()->fullUrlWithQuery(['by' => 'description', 'order' => $order === 'desc' ? 'asc' : 'desc']) }}">{{ __('Description') }}</a>
						            </th>
						            <th class="header">{{ __('Dimensions (base sheet)') }}</th>
						            <th class="header header-sort-{{ $by === 'w' ? ($order === 'desc' ? 'down' : 'up') : '' }}">
					                	<a href="{{ request()->fullUrlWithQuery(['by' => 'w', 'order' => $order === 'desc' ? 'asc' : 'desc']) }}">{{ __('Specific weights') }}</a>
						            </th>
					                <th class="header">{{ __('Edit') }}</th>
					            </tr>
					            </thead>
					            <tbody>
					            	@if($papers->count())
					            		@foreach ($papers as $paper)
							                <tr class="clickable-row" data-href="{{ route('papers.edit', $paper->id) }}">
							                    <td>{{ $paper->name }}</td>
							                    <td>{{ $paper->description }}</td>
							                    <td>{{ $paper->baseSheet->name }}</td>
							                    <td>{{ $paper->specific_weight }}</td>
							                    <td><i class="fa fa-caret-right"></i></td>
							                </tr>
							            @endforeach
						              @else
						              	<tr class="clickable-row" data-href="">
						                    <td colspan="5">{{ __('No entries') }}</td>
						                </tr>
						              @endif
					            </tbody>
					        </table>
					    </div>

					    <div class="pagination mt-5 w-100 align-items-center">

					    	{{ $papers->links() }}

					    </div>

            		</div>
            	</div>

            </div>


            <div id="sidebar" class="col-auto">

                <div class="text-center mt-5">
                    <a class="btn btn-primary my-1 w-100" href="{{ route('papers.create') }}">{{ __('Add new paper') }}</a>
                    
                    <br/>

                    <a class="btn btn-secondary my-1 w-100" href="/">{{ __('Back to home page') }}</a>
                </div>
                
            </div>

        </form>

    </div>

</div>

@endsection