routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

	if ( auth()->id() ) {

		return redirect()->route('home');
	}

    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('base-sheets', 'BaseSheetController');
Route::resource('press-sheets', 'PressSheetController');
Route::get('press-sheets/create/{baseSheetId?}', 'PressSheetController@create')->name('press-sheets.create');
Route::post('press-sheets/filter', 'PressSheetController@filter')->name('press-sheets.filter');
Route::resource('clients', 'ClientController');
Route::resource('papers', 'PaperController');
Route::resource('machines', 'MachineController');



// Route::fallback(function () {
//     return view('welcome');
// });

app/Machine.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Machine extends Model
{
    const TABLE = 'machines';
    const PRESS_SHEET_PIVOT_TABLE = 'machine_press_sheet';
    
    protected $table = self::TABLE; 

    protected $fillable = [
        'name',
        'description',
        'work_and_turn',
        'colour_no',
        'makulatur',
        'plate_price',
        'start_price',
        'price_per_tausand',
        'start_price_per_hour',
        'price_per_hour ',
        'start_time',
        'sheets_per_hour'
    ];

    public function pressSheets()
    {
        return $this->belongsToMany(PressSheet::class, self::PRESS_SHEET_PIVOT_TABLE);
    }

    public static function boot() {
        
        parent::boot();

        static::deleting(function($machine) { // before delete() method call this
             $machine->pressSheets()->detach();
        });
    }
}

app/Http/Controllers/MachineController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\MachineRequest;
use App\Machine;
use App\Services\MachineService;
use App\Services\PressSheetService;
use Illuminate\Http\Request;

class MachineController extends Controller
{
    const ATTRIBUTES = [
        'name',
        'description',
        'work_and_turn',
        'colour_no',
        'makulatur',
        'plate_price',
        'start_price',
        'price_per_tausand',
        'start_price_per_hour',
        'price_per_hour ',
        'start_time',
        'sheets_per_hour'
    ];

    private $machineService;
    private $pressSheetService;
    
    public function __construct( MachineService $machineService, PressSheetService $pressSheetService ) {
        
        $this->middleware(['auth', 'verified']);

        $this->machineService = $machineService;
        $this->pressSheetService = $pressSheetService;
    }
    
    public function index() {

        $machines = $this->machineService->getAll();

        return view('machines.index', compact('machines'));
    }

    public function create() {
        
        $press_sheets = $this->pressSheetService->getAll();

        return view('machines.create', compact('press_sheets'));
    }

    public function store( MachineRequest $request ) {
        
        $attributes = $request->only(self::ATTRIBUTES);
        $relations = $request->only('press_sheets');

        try {

            $this->machineService->store( $attributes, $relations );

        }  catch (\Exception $exception) {
            return redirect()->back()
                ->with([
                    'status'  => 'danger',
                    'message' => 'Error: ' . $exception->getMessage()
                ])
                ->withInput();
        }

       return redirect()->route('machines.index');
    }

    public function edit( Int $id ) {
        
        $press_sheets = $this->pressSheetService->getAll();
        $machine = $this->machineService->getById( $id );

        return view('machines.edit', compact('machine', 'press_sheets'));
    }

    public function update( MachineRequest $request, Int $id ) {
        
        $attributes = $request->only(self::ATTRIBUTES);
        $relations = $request->only('press_sheets');

        try {

            $this->machineService->update( $id, $attributes, $relations );

        } catch (Exception $exception) {
            
            return redirect()->back()
                ->with([
                    'status'  => 'danger',
                    'message' => 'Error: ' . $exception->getMessage()
                ])
                ->withInput();
        }

        return redirect()->back();
    }

    public function destroy( Int $id) {
        
        try {

            $this->machineService->delete( $id );

        } catch (Exception $exception) {
            
            return redirect()->back()
                ->with([
                    'status'  => 'danger',
                    'message' => 'Error: ' . $exception->getMessage()
                ])
                ->withInput();
        }

        $message = __('Press deleted.');

        return redirect()->route('machines.index')->with([
                    'status'  => 'success',
                    'message' => $message
                ]);
    }
}

resources/views/machines/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="">

        <form action="{{ route('machines.store') }}" method="POST" class="row px-3 needs-validation" novalidate>

            @csrf

            <div class="col">

                <div class="row">
                    <div class="col">
                        
                        <h1 class="mt-5">{{ __('Machine') }}</h1>

                        <h2>{{ __('Add new press') }}</h2>
                        <hr>

                        @include('partials.alerts')

                        @include('machines.form-fields')

                    </div>
                </div>
            </div>


            <div id="sidebar" class="col-auto">

                <div class="text-center mt-5">
                    <button type="submit" class="btn btn-primary my-1 w-100">{{ __('Save') }}</button>
                    <a href="{{ route('machines.index') }}" class="btn btn-secondary my-1 w-100">{{ __('Cancel') }}</a>
                    
                    <br/>

                    <a class="btn btn-secondary my-1 w-100" href="/">{{ __('Back to home page') }}</a>
                </div>

            </div>

        </form>

    </div>

</div>

@endsection

resources/views/machines/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="">

        <form action="{{ route('machines.update', $machine->id )}}" method="POST" class="row px-3 needs-validation" novalidate>

            @csrf
            @method('PATCH')

            <input type="number" class="d-none" name="id" value="{{ $machine->id }}" />

            <div class="col">

                <div class="row">
                    <div class="col">
                        
                        <h1 class="mt-5">{{ __('Machine') }}</h1>

                        <h2>{{ __('Edit entry') }}</h2>
                        <hr>

                        @include('partials.alerts')

                        @include('machines.form-fields')

                    </div>
                </div>

            </div>


            <div id="sidebar" class="col-auto">

                <div class="text-center mt-5">
                    <button type="submit" class="btn btn-primary my-1 w-100">{{ __('Save') }}</button>

                    <a href="#" class="btn btn-danger my-1 w-100" onclick="if(confirm('{{ __('Are you sure?') }}')){
                        event.preventDefault();document.getElementById('delete_machine').submit()
                    }">{{ __('Delete') }}</a>
                    <a href="{{ route('machines.index') }}" class="btn btn-secondary my-1 w-100">{{ __('Cancel') }}</a>
                    
                    <br/>

                    <a class="btn btn-secondary my-1 w-100" href="/">{{ __('Back to home page') }}</a>
                </div>
                
            </div>

        </form>

    </div>

</div>


<form id="delete_machine" action="{{ route('machines.destroy', $machine->id) }}"
      method="POST" style="display: none;" onsubmit="return confirm('{{ __('Are you sure?') }}')">
    @method('DELETE')
    @csrf
</form>

@endsection

resources/views/machines/form-fields.blade.php
<div>
    <div class="form-group row">
        <label for="name" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Title') }}</label>
        <div class="col-lg-5">
            <input type="text" class="form-control form-control-sm {{ $errors->has('name') ? 'is-invalid' : '' }}" id="name" name="name" placeholder="[{{ __('Title') }}]" value="{{ old('name', $machine->name ?? '') }}" required />
            <div class="invalid-feedback">
                @if ($errors->has('name'))
                    @foreach ($errors->get('name') as $message)
                        {{ $message }}
                    @endforeach
                @else
                    {{ __('This field is mandatory!') }}
                @endif
            </div>
        </div>
    </div>                            
    
    <div class="form-group row">
        <label for="description" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Description') }}</label>
        <div class="col-lg-5">
            <textarea type="text" class="form-control form-control-sm" id="description" name="description" rows="3" placeholder="[{{ __('Description') }}]">{{ old('description', $machine->description ?? '') }}</textarea>
        </div>
    </div>

    <fieldset class="form-group">
        <div class="row">
            <label for="work_and_turn" class="col-form-label col-form-label-sm col-lg-2">{{ __('Work and turn (capable)') }}</label>
            <div class="col-lg-5">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="work_and_turn" id="wt_yes" value="1" {{ old('work_and_turn', $machine->work_and_turn ?? false) ? 'checked' : '' }} />
                    <label class="form-check-label col-form-label-sm" for="wt_yes">{{ __('Yes') }}</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="work_and_turn" id="wt_no" value="0" {{ old('work_and_turn', $machine->work_and_turn ?? false) ? 'checked' : '' }} />
                    <label class="form-check-label col-form-label-sm" for="wt_no">{{ __('No') }}</label>
                </div>
            </div>
        </div>
    </fieldset>

    <div class="form-group row">
        <label for="cn" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Number of colours in one pass') }}</label>
        <div class="col-lg-5">
            <input type="number" class="form-control form-control-sm {{ $errors->has('colour_no') ? 'is-invalid' : '' }}" id="cn" name="colour_no" placeholder="[{{ __('Number of colours in one pass') }}]" value="{{ old('colour_no', $machine->colour_no ?? '') }}" required />
            <div class="invalid-feedback">
                @if ($errors->has('colour_no'))
                   @foreach ($errors->get('colour_no') as $message)
                        {{ $message }}
                    @endforeach
                @else
                    {{ __('This field is mandatory!') }}
                @endif
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="mk" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Makulatur per colour') }}</label>
        <div class="col-lg-5">
            <input type="number" class="form-control form-control-sm {{ $errors->has('makulatur') ? 'is-invalid' : '' }}" id="mk" name="makulatur" placeholder="[{{ __('Makulatur per colour') }}]" value="{{ old('makulatur', $machine->makulatur ?? '') }}" required />
            <div class="invalid-feedback">
                @if ($errors->has('makulatur'))
                   @foreach ($errors->get('mmakulaturk') as $message)
                        {{ $message }}
                    @endforeach
                @else
                    {{ __('This field is mandatory!') }}
                @endif
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="pp" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Plate price') }}</label>
        <div class="col-lg-5">
            <input type="number" class="form-control form-control-sm {{ $errors->has('pp') ? 'is-invalid' : '' }}" id="pp" name="plate_price" placeholder="[EUR]" value="{{ old('plate_price', $machine->plate_price ?? '') }}" />
            <div class="invalid-feedback">
                @if ($errors->has('plate_price'))
                   @foreach ($errors->get('plate_price') as $message)
                        {{ $message }}
                    @endforeach
                @endif
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="sp" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Starting price (price up to 1000 sheets, per colour)') }}</label>
        <div class="col-lg-5">
            <input type="number" class="form-control form-control-sm {{ $errors->has('start_price') ? 'is-invalid' : '' }}" id="sp" name="start_price" placeholder="[EUR]" value="{{ old('start_price', $machine->start_price ?? '') }}" />
            <div class="invalid-feedback">
                @if ($errors->has('start_price'))
                   @foreach ($errors->get('start_price') as $message)
                        {{ $message }}
                    @endforeach
                @endif
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="ppt" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Price per 1000 seets (after first 1000, per colour)') }}</label>
        <div class="col-lg-5">
            <input type="number" class="form-control form-control-sm {{ $errors->has('price_per_tausand') ? 'is-invalid' : '' }}" id="ppt" name="price_per_tausand" placeholder="[EUR]" value="{{ old('price_per_tausand', $machine->price_per_tausand ?? '') }}" />
            <div class="invalid-feedback">
                @if ($errors->has('price_per_tausand'))
                   @foreach ($errors->get('price_per_tausand') as $message)
                        {{ $message }}
                    @endforeach
                @endif
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="sph" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Starting price when calculating per hour (preparing)') }}</label>
        <div class="col-lg-5">
            <input type="number" class="form-control form-control-sm {{ $errors->has('start_price_per_hour') ? 'is-invalid' : '' }}" id="sph" name="start_price_per_hour" placeholder="[EUR]" value="{{ old('start_price_per_hour', $machine->start_price_per_hour ?? '') }}" />
            <div class="invalid-feedback">
                @if ($errors->has('start_price_per_hour'))
                   @foreach ($errors->get('start_price_per_hour') as $message)
                        {{ $message }}
                    @endforeach
                @endif
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="pph" class="col-lg-2 col-form-label col-form-label-sm">{{ __('Price per hour') }}</label>
        <div class="col-lg-5">
            <input type="number" class="form-control form-control-sm {{ $errors->has('price_per_hour') ? 'is-invalid' : '' }}" id="pph" name="price_per_hour" placeholder="[EUR]" value="{{ old('price_per_hour', $machine->price_per_hour ?? '') }}" />
            <div class="invalid-feedback">
                @if ($errors->has('price_per_hour'))
                   @foreach ($errors->get('price_per_hour') as $message)
                        {{ $message }}
                    @endforeach
                @endif
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="st" class="col-lg-2 col-form-label col-form-label-sm">{{ __('How long it take to start printing') }}</label>
        <div class="col-lg-5">
            <input type="number" class="form-control form-control-sm {{ $errors->has('start_time') ? 'is-invalid' : '' }}" id="st" name="start_time" placeholder="[min.]" value="{{ old('start_time', $machine->start_time ?? '') }}" />
            <div class="invalid-feedback">
                @if ($errors->has('start_time'))
                   @foreach ($errors->get('start_time') as $message)
                        {{ $message }}
                    @endforeach
                @endif
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="stsph" class="col-lg-2 col-form-label col-form-label-sm">{{ __('How many seets per hour') }}</label>
        <div class="col-lg-5">
            <input type="number" class="form-control form-control-sm {{ $errors->has('sheets_per_hour') ? 'is-invalid' : '' }}" id="stsph" name="sheets_per_hour" placeholder="[kom]" value="{{ old('sheets_per_hour', $machine->sheets_per_hour ?? '') }}" />
            <div class="invalid-feedback">
                @if ($errors->has('sheets_per_hour'))
                   @foreach ($errors->get('sheets_per_hour') as $message)
                        {{ $message }}
                    @endforeach
                @endif
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="sheet_ids" class="col-lg-2 col-form-label col-form-label-sm">
            {{ __('Press sheets it can print on') }}
        </label>
        <div class="col-lg-5">
            <select class="selectpicker col-12 px-0" id="area_ids" name="press_sheets[]" multiple data-none-selected-text="({{ __('leave blank for all') }})">

                @forelse($press_sheets as $press_sheet)
                    <option value="{{ $press_sheet['id'] }}"
                            {{ in_array($press_sheet->id, old('sheets', ($machine ?? []) ? ($machine->pressSheets->pluck('id')->toArray()) : [])) ? 'selected' : '' }}>
                        {{ $press_sheet->name }}
                    </option>
                @empty
                    {{ __('No entries') }}
                @endforelse
            </select>
        </div>
    </div>
</div>

resources/views/machines/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="">

        <form class="row px-3">

            @csrf

            <div class="col">

            	<div class="row">
            		<div class="col">
            			
            			<h1 class="mt-5 mb-2">{{ __('Machine') }}</h1>

            			<h2>{{ __('Here you can define presses and printers') }}</h2>
		            	<hr>

		            	@include('partials.alerts')

		            	<div>
					        <table class="ck" data-sort="table">
					            <thead>
					            <tr>
					                <th class="header">{{ __('Title') }}</th>
					                <th class="header">{{ __('Description') }}</th>
					                <th class="header">{{ __('Edit') }}</th>
					            </tr>
					            </thead>
					            <tbody>
					            	@if($machines->count())
					            		@foreach ($machines as $machine)
							                <tr class="clickable-row" data-href="{{ route('machines.edit', $machine->id) }}">
							                    <td>{{ $machine->name }}</td>
							                    <td>{{ $machine->description }}</td>
							                    <td><i class="fa fa-caret-right"></i></td>
							                </tr>
							            @endforeach
						              @else
						              	<tr class="clickable-row" data-href="">
						                    <td colspan="3">{{ __('No entries') }}</td>
						                </tr>
						              @endif
					            </tbody>
					        </table>
					    </div>

            		</div>
            	</div>
            </div>


            <div id="sidebar" class="col-auto">

                <div class="text-center mt-5">
                    <a class="btn btn-primary my-1 w-100" href="{{ route('machines.create') }}">{{ __('Add new press') }}</a>
                    
                    <br/>

                    <a class="btn btn-secondary my-1 w-100" href="/">{{ __('Back to home page') }}</a>
                </div>
                
            </div>

        </form>

    </div>

</div>

@endsection